name: energydata-env
dependencies:
- openssl=1.0.2h=1
- pip=8.1.2=py27_0
- python=2.7.12=0
- readline=6.2=2
- setuptools=23.0.0=py27_0
- sqlite=3.13.0=0
- tk=8.5.18=0
- wheel=0.29.0=py27_0
- zlib=1.2.8=3
- pip:
  - appnope==0.1.0
  - backports-abc==0.4
  - backports.shutil-get-terminal-size==1.0.0
  - backports.ssl-match-hostname==3.5.0.1
  - certifi==2016.2.28
  - configparser==3.5.0
  - cycler==0.10.0
  - decorator==4.0.9
  - entrypoints==0.2.2
  - functools32==3.2.3.post2
  - gnureadline==6.3.3
  - ipykernel==4.3.1
  - ipython==4.2.1
  - ipython-genutils==0.1.0
  - ipywidgets==5.1.5
  - jinja2==2.8
  - jsonschema==2.5.1
  - jupyter==1.0.0
  - jupyter-client==4.3.0
  - jupyter-console==4.1.1
  - jupyter-core==4.1.0
  - markupsafe==0.23
  - matplotlib==1.5.1
  - mistune==0.7.3
  - nbconvert==4.2.0
  - nbformat==4.0.1
  - networkx==1.11
  - notebook==4.2.1
  - numpy==1.11.0
  - pandas==0.18.1
  - pathlib2==2.1.0
  - pexpect==4.1.0
  - pickleshare==0.7.2
  - pillow==3.2.0
  - plotly==1.9.9
  - ptyprocess==0.5.1
  - pygments==2.1.3
  - pyparsing==2.1.1
  - python-dateutil==2.5.2
  - pytz==2016.3
  - pyzmq==15.2.0
  - qtconsole==4.2.1
  - requests==2.9.1
  - scikit-learn==0.17.1
  - scipy==0.17.0
  - seaborn==0.7.1
  - simplegeneric==0.8.1
  - singledispatch==3.4.0.3
  - six==1.10.0
  - terminado==0.6
  - tornado==4.3
  - traitlets==4.2.2
  - widgetsnbextension==1.2.3

